# Generated by Django 5.2.15 on 2026-06-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='full name'),
        ),
    ]
