# Generated by Django 5.2.15 on 2026-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='image')),
                ('link_url', models.URLField(blank=True, verbose_name='link URL')),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=100, verbose_name='button text')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='content_ban_is_acti_20d512_idx')],
            },
        ),
    ]
