# Generated by Django 5.2.15 on 2026-06-16 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(db_index=True, max_length=255, verbose_name='store name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'sellers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_name'], name='vendors_sel_store_n_9dea3c_idx'), models.Index(fields=['is_approved', '-created_at'], name='vendors_sel_is_appr_36f5b9_idx')],
            },
        ),
    ]
