# Generated by Django 5.2.15 on 2026-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/%Y/%m/', verbose_name='logo'),
        ),
    ]
